name: Append New Record to CSV

on:
  issues:
    types: [opened]

jobs:
  append_to_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas

      - name: Check if issue has 'new' label
        id: check_label
        run: |
          echo "Issue labels: ${{ toJson(github.event.issue.labels) }}"
          echo "check_label=has_label::$(echo '${{ github.event.issue.labels }}' | grep -q 'new' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Extract issue content and append to CSV
        if: steps.check_label.outputs.has_label == 'true'
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          import os
          import pandas as pd

          # Extract issue content
          issue_body = os.getenv("ISSUE_BODY")
          lines = issue_body.splitlines()
          record = {}

          # Parse fields from issue body
          for line in lines:
              if line.startswith("**Name**:"):
                  record["Name"] = line.split("**Name**:")[1].strip()
              elif line.startswith("**Arabic Name**:"):
                  record["Arabic Name"] = line.split("**Arabic Name**:")[1].strip()
              elif line.startswith("**Home Town**:"):
                  record["Home Town"] = line.split("**Home Town**:")[1].strip()
              elif line.startswith("**Home Town in Arabic**:"):
                  record["Home Town in Arabic"] = line.split("**Home Town in Arabic**:")[1].strip()
              elif line.startswith("**Funeral Town**:"):
                  record["Funeral Town"] = line.split("**Funeral Town**:")[1].strip()
              elif line.startswith("**Funeral Town in Arabic**:"):
                  record["Funeral Town in Arabic"] = line.split("**Funeral Town in Arabic**:")[1].strip()
              elif line.startswith("**Day**:"):
                  record["Day"] = line.split("**Day**:")[1].strip()
              elif line.startswith("**Hour**:"):
                  record["Hour"] = line.split("**Hour**:")[1].strip()
              elif line.startswith("**Image Path**:"):
                  record["Image Path"] = line.split("**Image Path**:")[1].strip()

          # Read the existing CSV file
          csv_file = "hezbollah-martyrs/hezbollah-losses-escalation.csv"
          df = pd.read_csv(csv_file)

          # Append the new record
          df = df.append(record, ignore_index=True)

          # Save the updated CSV file
          df.to_csv(csv_file, index=False)

      - name: Commit and push changes
        if: steps.check_label.outputs.has_label == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add hezbollah-martyrs/hezbollah-losses-escalation.csv
          git commit -m "Append new record to CSV from Issue #${{ github.event.issue.number }}"
          git push
